### ISSUE TITLE
Update Spaces

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/spacey#23]
Remove Classroom 13 
Add Front Lounge, Lobby Classroom, Jobs Room, Gates Room, Board Room, 12th Floor A Space, 12th Floor B Space, 12th Floor C Space, OpenGovHub

**Comment by tylercrosse** [comment]
Do you know the capacity of all of the rooms, including classrooms 1-6?

**Comment by amychoi** [comment]
![space capacities](https://cloud.githubusercontent.com/assets/15385443/15868418/bf456b84-2cb5-11e6-97d0-0233124e13ec.png)

**Comment by bmartinowich** [comment]
@tylercrosse See above ^

**Comment by tylercrosse** [comment]
I added an additional field for events to be able to indicate what style they are. @amychoi How do you feel about calling them "Classroom style" and "Presentation style"? Lecture to me is easy to confuse with class

**Comment by amychoi** [comment]
Lecture style works well because it translates for my team to equal chairs
only, no tables. I also have lecture style listed as an option already on
the space request form most full-time staff use, so I want to keep the
wording consistent.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by tylercrosse** [comment]
Cool will do, thanks!

**Comment by tylercrosse** [comment]
PR #28

**Comment by amychoi** [comment]
![screen shot 2016-06-09 at 2 44 13 pm](https://cloud.githubusercontent.com/assets/15385443/15942032/b2581092-2e50-11e6-82dc-1c1fb4ad40b5.png)
@tylercrosse

**Comment by tylercrosse** [comment]
see pull #43
